version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./.docker/mongodb/data/configdb/:/data/configdb/
      - ./.docker/mongodb/data/db/:/data/db/
    environment:
      - MONGO_INITDB_DATABASE=fitnessdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'
